#!/bin/bash

usage() {
  cat 1>&2 <<EOF
Installer of Terrabutler

USAGE:
    install [FLAGS] [OPTIONS]

FLAGS:
    -h, --help                Prints this help menu

OPTIONS:
    -i, --install-dir <path>  Directory where Terrabutler will be installed. By
                              default, this directory is: /usr/share/terrabutler

    -b, --bins-dir <path>     The directory where the binaries of the Terrabutler
                              are stored. By default, the directory is: /usr/bin/
EOF
}

cli() {
  while test $# -gt 0
  do
    key="$1"
	case "$key" in
    -i|--install-dir)
      USER_INSTALL_DIR="$2"
		shift
    ;;
    -b|--bins-dir)
      USER_BIN_DIR="$2"
		shift
    ;;
    -h|--help)
      usage
      exit 0
    ;;
	  *)
	   printf "Argument unrecognized: '%s'" "$1"
	   exit 1
	  ;;
    esac
	shift
  done
}

apply_env () {
  INSTALLER_DIR=$( cd "$( dirname "$0" )" >/dev/null 2>&1 && pwd )
  INSTALLER_DIST_DIR="$INSTALLER_DIR/dist/."
  INSTALL_DIR=${USER_INSTALL_DIR:-/usr/local/share/terrabutler}
  BINS_DIR=${USER_BIN_DIR:-/usr/local/bin}
  BIN_FILE="$BINS_DIR/terrabutler"
}

check_preexisting_install () {
  if [ -d "$INSTALL_DIR" ] && [ -f "$BIN_FILE" ]; then
    echo "Found preexisting Terrabutler installation: $INSTALL_DIR."

    if [ "${FORCE_INSTALL:-no}" == "yes" ] ; then
        echo "Replacing preexisting Terrabutler installation (FORCE_INSTALL=yes)"
        rm -rf "$INSTALL_DIR" "$BIN_FILE"
        return
    fi

    read -r -p "Do you want to replace it? [y/N] " response
    case "$response" in
        [yY])
            rm -rf "$INSTALL_DIR" "$BIN_FILE"
            ;;
        *)
            echo "Aborting installation."
            exit 1
            ;;
    esac
  fi
}

install () {
  # Copy distribution files to the installation directory
  mkdir -p "$INSTALL_DIR"
  cp -a "$INSTALLER_DIST_DIR" "$INSTALL_DIR" || exit 1
  
  # Copy binaries to user's bin directory
  mkdir -p "$BINS_DIR"
  ln -s "$INSTALL_DIR/terrabutler" "$BIN_FILE" || exit 1

  printf "Install has finished successfully.\nYou may now use '%s' command.\n" "$BIN_FILE"
}

main () {
  cli "$@"
  apply_env
  check_preexisting_install
  install
}

main "$@"
