#!/bin/bash

usage() {
  cat 1>&2 <<EOF
Installer of Terrabutler

USAGE:
    install [FLAGS] [OPTIONS]

FLAGS:
    -h, --help                Prints this help menu

OPTIONS:
    -i, --install-dir <path>  Directory where Terrabutler will be installed. By
                              default, this directory is: /usr/share/terrabutler

    -b, --bins-dir <path>     The directory where the binaries of the Terrabutler
                              are stored. By default, the directory is: /usr/bin/
EOF
}

cli() {
  while test $# -gt 0
  do
    key="$1"
	case "$key" in
    -i|--install-dir)
      USER_INSTALL_DIR="$2"
		shift
    ;;
    -b|--bins-dir)
      USER_BIN_DIR="$2"
		shift
    ;;
    -h|--help)
      usage
      exit 0
    ;;
	  *)
	   printf "Argument unrecognized: '%s'" "$1"
	   exit 1
	  ;;
    esac
	shift
  done
}

check_preexisting_install () {
  if [ -d "${USER_INSTALL_DIR:-/usr/share/terrabutler}" ] && [ -f "${USER_BIN_DIR:-/usr/bin/terrabutler}" ]; then
    echo "Found preexisting Terrabutler installation: ${CURRENT_INSTALL_DIR:-/usr/share/terrabutler}."
    read -r -p "Do you want to replace it? [y/N] " response
    case "$response" in
        [yY])
            ;;
        *)
            echo "Aborting installation."
            exit 1
            ;;
    esac
  fi

}

install () {
  INSTALLER_DIR=$(pwd)
  INSTALL_DIR=${USER_INSTALL_DIR:-/usr/share/terrabutler}
  BINS_DIR=${USER_BIN_DIR:-/usr/bin}

  # Copy distribution files to the installation directory
  mkdir -p "$INSTALL_DIR" || exit 1
  cp -a "$INSTALLER_DIR/dist/." "$INSTALL_DIR" || exit 1
  
  # Copy binaries to user's bin directory
  mkdir -p "$BINS_DIR" || exit 1
  ln -s "$INSTALLER_DIR/dist/terrabutler" "BINS_DIR/terrabutler" || exit 1
}

main () {
  cli "$@"
}

main "$@"